#Reproducible worker job
#Thu Sep 24 06:31:28 UTC 2026
algorithm=GRASP
budget=1
config=/mnt/data/paqrap_work/pucp-2026-2-1inf54-software-design-development-project-feature-experimentos-grasp-v2/PaqRap_Experimentos_GRASP_SA/paqrap-experimentacion/evidencia/v3/tiny-budget.properties
expected_input_sha256=34eb25bdacb5c7f31016ea9e8bdb3ff86734f6728afb668c1761254cbb4804fe
prefix=/mnt/data/paqrap_work/pucp-2026-2-1inf54-software-design-development-project-feature-experimentos-grasp-v2/PaqRap_Experimentos_GRASP_SA/paqrap-experimentacion/evidencia/v3/tiny-budget/jobs/EDGE-r1-b1-GRASP
repetition=1
root=/mnt/data/paqrap_work/pucp-2026-2-1inf54-software-design-development-project-feature-experimentos-grasp-v2/PaqRap_Experimentos_GRASP_SA/paqrap-experimentacion
run_id=EDGE-r1-b1-GRASP
scenario=EDGE,NORMAL,SYNTHETIC,20,921,2026-09-09,7,8
seed=42
