#Reproducible worker job
#Wed Sep 30 02:43:25 UTC 2026
algorithm=SA
budget=1
config=/mnt/data/paqrap_actualizado/paqrap-experimentacion/evidencia/flex1/one-ms.properties
expected_input_sha256=252c1c62b81336a2515c37441f9bc819b2eca5c78f3e78dd7d8925d9880b4587
prefix=/mnt/data/paqrap_actualizado/paqrap-experimentacion/evidencia/flex1/one-ms/jobs/EDGE-r1-b1-SA
repetition=1
root=/mnt/data/paqrap_actualizado/paqrap-experimentacion
run_id=EDGE-r1-b1-SA
scenario=EDGE,NORMAL,SYNTHETIC,3,1101,2026-09-09,7,8
seed=42
